#!/usr/bin/env python2.7

from __future__ import print_function
import sys
import os
import argparse
from clinphen_src import interface

def main():
  interface.run_gui()

if __name__ == "__main__":
  main()
